name: Build CMAKE

on: [push, pull_request]

env:
  CMAKE_VERSION: 3.18.1
  BUILD_TYPE: Release


jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config-os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
          name: "Ubuntu Latest GCC", artifact: "Linux.7z",
          os: ubuntu-latest,
          cc: "gcc", cxx: "g++"
        }
  
  steps:
  - uses: actions/checkout@v1

  - name: Download and bootstrap CMake
    shell: bash
    run: |
      if [ "$RUNNER_OS" == "Linux" ]; then
        cmake_suffix="linux-x86_64.tar.gz"
        cmake_dir="cmake-${cmake-version}-Linux-x86_64/bin"
      fi

      curl -o ${cmake_suffix} https://github.com/Kitware/CMake/releases/download/v${cmake_version}/cmake-${cmake_version}-${cmake_suffix}
      tar -xvf ${cmake_suffix}

      echo "${cmake_dir}" >> $GITHUB_PATH

      